---
title: "Fluxicon Purchasing Example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center")

library(tidyverse)
library(lubridate)
library(bupaR)
library(processanimateR)
```

```{r}
Roh <- read.csv("PurchasingExample.csv")

Log <- Roh %>% 
  mutate(Activity = gsub("Supplier's", "Suppliers", Roh$Activity)) %>% # remove ' to avoid syntax error with process_map function
  gather(Start.Timestamp, Complete.Timestamp, key = "Status", value = "Time") %>% # Transpose Start/Complete timestamps to long format
  mutate(Time = ymd_hms(Time)) %>%
  mutate(activity_instance = 1:nrow(.)) %>% # Add artificial activity_instance_id
  eventlog(case_id = "Case.ID",
           activity_id = "Activity",
           activity_instance_id = "activity_instance",
           lifecycle_id = "Status",
           timestamp = "Time",
           resource_id = "Resource")

Log %>% animate_process(token_color = "orange")
```

Compared with [this animation](https://www.youtube.com/watch?v=-umuLfQWCLo) of the same process in Disco, the bottleneck at the activity "Analyze Request for Quotation" is not visible here. Perhaps there might be a way to show the movement of the tokens along the arrows and keep the different tokens separate from each other. This could make congestions more visible.